analysis.json
bower.json
demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
test/index.html
test/scrollable-viewport-test.html
vaadin-dropdown-menu.html

Connected to https://github.com/vaadin/vaadin-core/issues/136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/4)

Initial alternative prototype functionality

---

demo/dropdown-menu-basic-demos.html
vaadin-dropdown-menu.html

Connected to https://github.com/vaadin/vaadin-core/issues/136
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/7)

Add slot for selected content

---

demo/dropdown-menu-basic-demos.html
vaadin-dropdown-menu.html

Connected to https://github.com/vaadin/vaadin-core/issues/136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/8)

Add placeholder

---

demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

I re-read the code to find use cases no covered in tests. This is jus a PR for adding those test definition blocks without any implementation which will be done in separated PR. At the same time I did some re-factoring of the code removing unused blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/16)

write new test cases that should be implemented

---

test/dropdown-menu-test.html
vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/17)

Do not fail if template or list is empty. Fixes #9

---

test/dropdown-menu-test.html
vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/18)

Fix double tab for moving out the focus. Fixes #10

---

demo/dropdown-menu-basic-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/25)

Replace external images with public domain ones. Fixes #20

---

test/dropdown-menu-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/22)

Adding missing tests

---

test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/24)

Slot name needs to be set via attribute in polyfilled browsers

---

analysis.json
bower.json
demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/19)

Fix tabIndex by extending control-state. Fixes #14

---

analysis.json
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Move css conditions to style block.
Fixes #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/26)

Use container element as focusable. 

---

analysis.json
bower.json
demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #15
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/28)

Select the appropriate item when value is set

---

bower.json

Fixes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/36)

Add missing iron-media-query dependency

---

analysis.json
vaadin-dropdown-menu.html

Fixes #33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/34)

Reflect opened state to attribute. Document available state attributes

---

analysis.json
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Connected to #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/37)

Converting invalid to property to match Flow checklist

---

analysis.json
vaadin-dropdown-menu.html

Fixes #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/49)

Document invalid state attribute available for styling

---

vaadin-dropdown-menu.html

Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/55)

Remove readonly attribute from the internal text-field

---

demo/dropdown-menu-basic-demos.html
demo/index.html

Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/50)

Update demo for required dropdown-menu

---

test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/61)

Keep dropdown-menu and internal text-field focused when opening

---

test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/65)

Wrap native input in a slot, use slot assignment to toggle

---

test/dropdown-menu-test.html
test/mock-item.html

Connected to #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/69)

Cleanup tests, avoid dependency on <vaadin-item>

---

analysis.json
demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #59
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/70)

Should be possible to specify the error message on a dropdown menu.

---

demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/66)

Do not validate initial dropdown menu value

---

demo/dropdown-menu-basic-demos.html

Fixes #73
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/74)

Fix wrapping prefix in the custom content demo [skip ci]

---

test/dropdown-menu-test.html
test/scrollable-viewport-test.html
vaadin-dropdown-menu.html

Fixes #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/75)

fix focus in mobile on close

---

test/.eslintrc.json
test/dropdown-menu-test.html
test/scrollable-viewport-test.html
vaadin-dropdown-menu.html

Fixes #48 
Listen to items-changed event to update items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/72)

Listen to items-changed event to update items

---

vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/78)

Fix width in internal text-field. Fixes #76

---

README.md

- add element functionality description
- remove obsolete `vertical` attribute from `vaadin-list-box` in inline demo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/79)

Actualize README.md

---

.travis.yml

Applying the change in [skeleton](https://github.com/vaadin/vaadin-element-skeleton/pull/77).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/80)

Remove xvfb for saucelabs. Use wct instead of polymer-cli

---

analysis.json
vaadin-dropdown-menu.html

Fixes #30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/71)

Set padding in vertical mode

---

test/dropdown-menu-test.html

Add test for checking `_phone` property and `phone` attribute
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/82)

Add test for checking _phone property and phone attribute

---

analysis.json
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Connected to #30 
Update bottom style with `--vaadin-overlay-viewport-bottom` property
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/81)

Update bottom style with --vaadin-overlay-viewport-bottom property

---

demo/dropdown-menu-basic-demos.html

Fixes #83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/84)

Fix error message demo: allow to deselect value

---

test/visual/dropdown-menu.html

Fixes #85 
Fix visual tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/88)

Fix visual tests

---

analysis.json
demo/dropdown-menu-basic-demos.html
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #86
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/89)

Implement read-only state

---

analysis.json
test/dropdown-menu-test.html
vaadin-dropdown-menu.html

Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/90)

Toggle has-value attribute on the text-field

---

demo/dropdown-menu-basic-demos.html
src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html
test/mock-item.html

Fixes #103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/106)

Preserve selected state on the cloned disabled item used as placeholder

---

theme/lumo/vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/113)

Use custom property

---

demo/demos.json
demo/dropdown-menu-basic-demos.html

Connected to https://github.com/vaadin/components-team-tasks/issues/347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)

Update the styling example

---

.travis.yml
test/dropdown-menu-test.html
test/external-imports.html
test/scrollable-viewport-test.html
wct.conf.js

Connected to vaadin/components-team-tasks#332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/121)

Use bare module specifiers in the P3 conversion

---

test/animations-test.html
test/test-suites.js

Connected to https://github.com/vaadin/vaadin-overlay/issues/80
The test suite to prove https://github.com/vaadin/vaadin-overlay/issues/80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116)

Add animation tests

---

bower.json
theme/material/vaadin-dropdown-menu-styles.html
theme/material/vaadin-dropdown-menu.html

Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127)

Adding theme/material

---

src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html

Fixes #130 #136 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/137)

Do not modify value

---

.travis.yml
analysis.json
bower.json
demo/dropdown-menu-basic-demos.html
src/vaadin-dropdown-menu.html
test/renderer.html
test/test-suites.js

Requires https://github.com/vaadin/vaadin-overlay/pull/96
Fixes #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/145)

Add renderer

---

analysis.json
src/vaadin-dropdown-menu.html
test/renderer.html

Please `bower link vaadin-overlay` from `throw-error` branch before testing.
Requires https://github.com/vaadin/vaadin-overlay/pull/104
Connected to https://github.com/vaadin/components-team-tasks/issues/391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/147)

Throw error when template and renderer are used simultaneously

---

demo/dropdown-menu-basic-demos.html
demo/dropdown-menu-styling-demos.html
demo/dropdown-menu-validation-demos.html

Fixes #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/149)

Update demos to prefer renderers

---

analysis.json
src/vaadin-dropdown-menu.html

Connected to vaadin/components-team-tasks#403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/151)

Remove Polymer mention in the API docs

---

demo/dropdown-menu-basic-demos.html
demo/dropdown-menu-validation-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/152)

Replace `new` with `createElement` in demos to avoid errors in P3

---

src/vaadin-dropdown-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/162)

Force rendering the overlay with renderer

---

demo/dropdown-menu-basic-demos.html
src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html
test/mock-item.html
test/renderer.html

Fix #138 and fixes mentioned issue with `lit-html` by using getter for `_overlayElement`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/157)

Set template with observer

---

bower.json
demo/dropdown-menu-styling-demos.html
demo/index.html
src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html

Connected to vaadin/vaadin-themable-mixin#12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/161)

Propagate theme attribute to internal components

---

demo/dropdown-menu-basic-demos.html
src/vaadin-dropdown-menu.html

Connected to https://github.com/vaadin/components-team-tasks/issues/416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/168)

Improve renderers docs [skip ci]

---

bower.json

Fixes #173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/174)

fix(package): add missing iron-resizable-behavior dependency

---

src/vaadin-select.html
test/mock-item.html
test/select-test.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/196)

Add change event

---

src/vaadin-select.html
test/renderer.html

Fixes https://github.com/vaadin/vaadin-select/issues/180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/198)

Update selected item on render

---

src/vaadin-select.html
test/accessibility-test.html
test/select-test.html
test/test-suites.js
test/visual/select.html

Fixes #191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/200)

fix(a11y): improve screen reader support

---

src/vaadin-select.html
test/select-test.html

fix: remove role attribute from cloned item

---

@types/interfaces.d.ts

fix: make renderer owner optional [skip ci]

---

@types/interfaces.d.ts

Cherry-pick of #229 to `master` branch.
Closes #228

fix: make renderer owner optional [skip ci] (#229)

---

src/vaadin-select.html

docs: add JSDoc for attributes [skip ci] (#231)

---

.github/workflows/sauce.yml

Same as https://github.com/vaadin/vaadin-grid/pull/2087

ci: do not trigger build for tags [skip ci]

---

README.md

chore: update status badges in README [skip ci]

---

src/vaadin-select.html
test/select-test.html

cherry pick of https://github.com/vaadin/web-components/pull/2232 for v14
Fixes vaadin/flow-components#955

fix: do not open the field on helper element click

---

src/vaadin-select.html

Bump web component version string to 2.4.1

chore: bump web component version string

---

src/vaadin-select.html
test/renderer.html

Cherry-pick of https://github.com/vaadin/web-components/pull/2995
Fixes https://github.com/vaadin/flow-components/issues/2299 for Vaadin 14
- Cherry-pick

fix: don't throw on render before adding to DOM

---

src/vaadin-select.html
test/.eslintrc.json
test/helpers.html
test/test-suites.js
test/validation.html

Backports the following PRs as part of an EoD task:
- https://github.com/vaadin/web-components/pull/4174

fix: prevent initial validation (CP: 14)

---

src/vaadin-select.html
test/helpers.html
test/validation.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/4097
Part of https://github.com/vaadin/web-components/issues/5763

feat: add methods to make setting invalid overridable (CP: 14)
