analysis.json
vaadin-dropdown-menu.html

Fixes #42 
Fixes #43  
Improve documentation to include **hints** and user-specific cases about `label`s, `value`, `placeholder` and `slots`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/46)

Improve documentation and update analysis.json

---

bower.json
demo/dropdown-menu-basic-demos.html
demo/index.html
src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html
theme/valo/vaadin-dropdown-menu.html

Fixes #94 
Depends on https://github.com/vaadin/vaadin-text-field/pull/181
- Remove wrapping example (doesn’t work with Valo)
- Remove tabindex demo (not a best practice)
- Use vaadin-demo-helpers shared styles
- Fix theme to work with latest vaadin-text-field and vaadin-valo-theme
updates
- Reflect `readonly` and `label` to the internal
dropdown-menu-text-field element (the theme uses these attributes)
- Change the label default value to `undefined` (the theme needs a
non-empty string to work correctly)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/93)

Update theme and demos

---

src/vaadin-dropdown-menu.html
theme/lumo/vaadin-dropdown-menu.html

This leaves the decision of the responsive behavior up to the theme to decide, and allows for example to use different behavior for Lumo and Material themes.
Remove the fixed `min-width` at the same time, as that is also the themes decision.
`vaadin-item` padding is handled by the `vaadin-list-box` theme (decouple the styles from `vaadin-dropdown-menu`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/100)

Move small viewport behavior styles from core to Lumo

---

src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html

Fix https://github.com/vaadin/components-team-tasks/issues/306
Restore `focus-ring` if component was firstly focused with <kbd>Tab</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/96)

Restore focus-ring if firstly was focused with Tab

---

src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html

Fixes #101 
The problem was in the initial slot distribution not being triggered, so I reorganised code to call `ShadyDOM.flush()` first and then `aappendChild`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/102)

Fix incorrect style scope on selected item for initial value

---

src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html

We apparently have copy-pasted Templatizer code from the `vaadin-context-menu` in several components, including this one. These `instanceProps` (see the [context-menu API docs](https://github.com/vaadin/vaadin-context-menu/blob/master/src/vaadin-context-menu.html#L166)) do not make any sense here and should be removed.
Also added the tests for data binding, based on vaadin/vaadin-notification#54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/105)

Add tests for data binding, remove unused instanceProps

---

analysis.json
src/vaadin-dropdown-menu.html
test/dropdown-menu-test.html
theme/lumo/vaadin-dropdown-menu.html

Allow the overlay to be sized according to the text-field width.
Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/107)

Expose `--vaadin-dropdown-menu-text-field-width` for the overlay

---

test/dropdown-menu-test.html
test/not-animated-styles.html

In the upcoming `vaadin-overlay` release, the animations feature is to be introduced, which in conjunction with the default animation styles in latest Lumo (`lumo-menu-overlay-core`) cause random failures.
Related https://github.com/vaadin/vaadin-combo-box/pull/632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/110)

Remove animations from tests

---

bower.json
demo/demos.json
demo/dropdown-menu-basic-demos.html
demo/dropdown-menu-styling-demos.html
demo/dropdown-menu-validation-demos.html
demo/index.html

Connects to "Guidelines for component examples"
- Removed “Value property” demo. It is already demoed in for example the first “Configuring the dropdown” demo.
- Removed Error message demo.
- Created Validation demo page with similar example as in combo-box.
- Created Styling demo page and moved “Styling” and “Customizing content” demos to that page.
- Added description to Custom label example.
- Modified “Configuring the dropdown” for it to have 1 empty row in between every example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/133)

Reorganize demo structure

---

bower.json
src/vaadin-dropdown-menu.html
test/renderer.html

Connected to https://github.com/vaadin/components-team-tasks/issues/409
Requires https://github.com/vaadin/vaadin-dropdown-menu/pull/157. After applying this [change](https://github.com/vaadin/vaadin-dropdown-menu/pull/157/files#diff-ecc026b97070b7868320a724532e6eadR374) the `_overlayElement` existence will be checked before setting the `renderer`, so there will be no need in checking it in `render` method with lit-element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/159)

Manual rendering of the content

---

demo/dropdown-menu-basic-demos.html
src/vaadin-dropdown-menu.html
test/renderer.html

Fixes #163 
Currently, some tests and demos (and parts of implementation related to pre-selecting first item with empty value) rely on menu element to be present before `opened` is set to `true`.
However, in the overlay we now switched to invoke `renderer` after `opened` and #162 was fixing it here, but introduced the regression so here is another fix for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/164)

Update renderer demos, rollback duplicate menu workarounds

---

demo/dropdown-menu-validation-demos.html

Form submission prevention is needed to prevent sending XHR, which produces 404 in all browsers, and hangs in IE11 for some reason related to `iron-request`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/169)

Fix validation demo renderer usage and form submission [skip ci]

---

README.md
bower.json

Fixes #176 
Note: `vaadin-select` still does not enforce you to use `vaadin-list-box`, so for the advanced users it is still possible to use import from `src` without getting the latter imported.
Someone might find this useful when working on a custom theme, e.g. using custom list-box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/177)

fix(bower): move vaadin-list-box and vaadin-item to dependencies

---

test/select-test.html

Fixes #189 
Looks like the test wasn't correct but only failed in IE11 for some reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-select/190)

test: check keyboard search for closed select

---

demo/select-basic-demos.html
demo/select-validation-demos.html

Make the basic demos shorter and easier to understand at a glance by using native `<template>` element (without Polymer template parsing) within renderer to avoid having a lot of JS just to create static DOM elements.
This can be further simplified later if we add a new feature which allows the user to specify this kind of non-Polymer `<template>` as a child of the `vaadin-select` without having to manually define a renderer method. It would work basically the same way as Polymer template now, but we would need some new attribute for the template to specify that it should not be parsed as a Polymer template (so that this kind of usage is future proof and doesn't advocate using Polymer only features).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

demo: simplify demos by using template more

---

@types/interfaces.d.ts
bower.json
gen-tsd.json
magi-p3-post.js
package.json
src/vaadin-select.html

Fixes #220 
Generated TS definitions look like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';
import {ControlStateMixin} from '@vaadin/vaadin-control-state-mixin/vaadin-control-state-mixin.js';
import {IronResizableBehavior} from '@polymer/iron-resizable-behavior/iron-resizable-behavior.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';
import {mixinBehaviors} from '@polymer/polymer/lib/legacy/class.js';
declare class SelectElement extends
ElementMixin(
ControlStateMixin( …
```

feat: prepare for TS defs generation

---

src/vaadin-select.html

Connected to vaadin/vaadin-core#257
Note, this is a PR for `2.3` branch. When cherry-picking it to master, we need to also include `helperText` property.

docs: add JSDoc for attributes [skip ci]

---

.github/workflows/sauce.yml

See https://github.community/t/github-actions-does-not-respect-skip-ci/17325
Note, the `github.event.commits.*.message` is only available for the `push` event, but not for the the `pull_request` 😕

ci: support skipping GitHub actions [skip ci]

---

src/interfaces.d.ts
src/vaadin-select.d.ts
src/vaadin-select.js

1. Added `@fires` annotations to enable VS Code lit-plugin code completion support.
2. Removed `path` from events typings as Polymer-specific and generally unused.

chore: add JSDoc for custom events [skip ci]

---

src/vaadin-select.d.ts
src/vaadin-select.js

Added a `change` event to align with the [API docs](https://cdn.vaadin.com/vaadin-select/3.0.0-alpha1/#/elements/vaadin-select#events).

chore: align JSDoc, add change event [skip ci]

---

src/vaadin-select.html
test/select-test.html

Backport https://github.com/vaadin/web-components/pull/3120 for V14

fix: restore select focus on fullscreen dropdown close (#3120)

---

src/vaadin-select.html
test/validation.html

Reverted https://github.com/vaadin/vaadin-select/pull/296/. It was decided not to backport the PRs preventing initial validation as it is a breaking change.
Part of https://github.com/vaadin/web-components/issues/5763

revert: "fix: prevent initial validation"
